on:
#   push:
#     branches: master
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install the dependencies
      run: python -m pip install -r scripts/requirements.txt
    - name: Build the binders
      run: |
        python binder/build.py
